### ISSUE TITLE
[Question] Can NetArchTest be used to enforce creation of a test class for every class in a project?

### ISSUE THREAD

**Issue by devantler** [BenMorris/NetArchTest#104]
Can this tool be used to enforce creation of unit test classes, and enforce their paths so e.g. a project with the following classes:

```
src/MyProject/Main.cs
src/MyProject/AFolder/AClass.cs
```

... would require an accompanying test project with the following classes:

```
tests/MyProject.Tests/Main.cs
tests/MyProject.Tests/AFolder/AClass.cs
```

**Comment by BenMorris** [comment]
I suppose we could add some kind of pattern matching method, e.g.
```
            var result = Types
                .That()
                .ResideInNamespace("Example")
                .Should()
                .HaveMatchingClass([some kind of funky regular expression])
                .GetResult();
```
However, I am not sure how useful this would be. I would be more inclined to use a test coverage tool like SonarQube for ensuring test coverage.
