### ISSUE TITLE
Highlighting "why" a type fails test

### ISSUE THREAD

**Issue by brettpostin** [BenMorris/NetArchTest#105]
In my tests I am outputting the types that fail the test. However what would be great is to identify the reason why that type fails the test.

e.g. 

```
var result = Types.InAssembly(typeof(Foo).Assembly)
    .Should()
    .OnlyHaveDependenciesOn(new string[] { "Bar" })
    .GetResult();

Assert.True(result.IsSuccessful, GetFailingTypes(result));

```

It would be great to see the dependencies causing the violation. Is there any means to do that at present?

**Comment by BenMorris** [comment]
I'm afraid not - the whole execution chain is predicated on building up a list of types that pass or fail rules (see [FunctionSequence.Execute()](https://github.com/BenMorris/NetArchTest/blob/367d3baea683a3a1110b744d301ae40b20985dcb/src/NetArchTest.Rules/FunctionSequence.cs#L45)). It doesn't retain any other metadata around _why_ a rule failed for each type.

**Comment by thomaseyde** [comment]
How can I vote for this as a feature request? I have struggled for two hour now to figure out why two simple types of mine fail.

**Comment by NeVeSpl** [comment]
Implementing that would require too many breaking changes, including performance profile/impact, thus I do not think that this will be ever implemented here. I have started the parallel project, that allows sending metadata alongside the type, and I have in mind this issue, but right now I do not have the motivation to push it forward.

**Comment by thomaseyde** [comment]
Fair enough. Thank you for the response 🙂

Mvh
Thomas Eyde

**Comment by brettpostin** [comment]
@thomaseyde we switched to [ArchUnitNET](https://github.com/TNG/ArchUnitNET), which according to nuget uses this project as a dependency and does report on failure reasons.
