### ISSUE TITLE
Only check for sub namespace of a certain namespace and ignore the rest

### ISSUE THREAD

**Issue by Velociraptor45** [BenMorris/NetArchTest#106]
Hey there,

let's say I have a solution with dependencies like
- System
- Microsoft
- Newtonsoft
- other namespaces included via packages
- MyNamespace.SubNamespace1
- MyNamespace.SubNamespace2
- ...
- MyNamespace.SubNamespace50
- ...

How do I check if an assembly in that solution references the namespace `MyNamespace.SubNamespace50` but not any of the others from `MyNamespace`?
Now, I could use `OnlyHaveDependenciesOn` but then I'd have to list all the other dependencies apart from `MyNamespace` in there also (like `System` or `Microsoft`) - but I don't care about them. I only want to check for `MyNamespace`. `NotHaveDependencyOn` is also not an option because then I'd have to list all the gazillion sub namespaces.
I couldn't find any `Except` method or something like that. Any idea on that?

**Comment by NeVeSpl** [comment]
You can only filter input types, that will be tested, there is no way to filter out dependencies (`Except`) in any way.

**Comment by Velociraptor45** [comment]
Ah, damn. What a pity. Thanks for the answer.
