### ISSUE TITLE
Types.InAssembly() does not allow additional directories for assembly resolution

### ISSUE THREAD

**Issue by BenPhegan** [BenMorris/NetArchTest#11]
Occasionally when resolving types from assemblies, not all the assemblies dependencies are present alongside the dependency.  This is addressed by Mono.Cecil.AssemblyDefinition.ReadAssembly by allowing the addition of ReaderParameters with defined additional SearchDirectories, however this is currently not exposed in NetArchTest.

**Comment by BenMorris** [comment]
Apologies for the delay on this. I'd like to get this covered by a unit test before pulling it in. Then again, this might be a bit tricky to do within the current unit test project. I will have a look over the weekend if you don't get the chance before then.

**Comment by BenPhegan** [comment]
No problem.  Happy to look at creating tests, as per my comment on the issue (https://github.com/BenMorris/NetArchTest/pull/12) I can look at this from two different ways.  One, less invasive to the code but harder to test would be to use the actual file system, generate assemblies via reflection within a directory tree, and use for testing.  The other is to use System.Io.Abstractions to use an IFileSystem, and reference this throughout the code rather than System.Io.  This is a much larger code change, however it would make testing the file system interaction significantly easier.  Do you have a preference?  For an example of the latter: https://github.com/BenPhegan/ReferenceChecker/blob/master/ReferenceChecker.Tests/AssemblyReferenceGrapherTests.cs#L21

**Comment by BenMorris** [comment]
I've had a look at this properly - apologies for the delay. My impulse would be to write less code and use the actual file system if at all possible. I guess you'll have to use a build action to make sure that a test dependency can always be found in the expected path. The implementation looks good to me though - if we can just get a test in then we're golden.
