### ISSUE TITLE
Get types for whole solution?

### ISSUE THREAD

**Issue by kristofferjalen** [BenMorris/NetArchTest#132]
Let's say I have three projects in the same solution:

- ProjectA
- ProjectB
- ArchitecturalTests

If I understand this correctly, invoking the `Types.InCurrentDomain()` method (with MSTest) in `ArchitecturalTests` will return only types in `ArchitecturalTests`. Thus, I have to use:

- `Types.InAssembly(typeof(SomeClassInProjectA).Assembly)` to get types in `ProjectA`
- `Types.InAssembly(typeof(SomeClassInProjectB).Assembly)` to get types in `ProjectB`

Can I get types from _all_ projects at once?

**Comment by NeVeSpl** [comment]
It depends what are references between projects. 

If ArchitecturalTests references ProjectA, and ProjectA references ProjectB, then all types should be available in the current domain. By reference I mean that exists at least one reference from one project to another in the compiled code (Assembly), not only on a project level.

NetArchTest does not have access to solution or even projects, it is why it operates on assemblies. NetAchTest can follow references between assemblies, but if there is not any reference between assemblies, there is no other way than explicitly providing assemblies in tests.

**Comment by kristofferjalen** [comment]
Thank you.
