### ISSUE TITLE
Support folder with both .Net assemblies and none .Net assemblies (c++)

### ISSUE THREAD

**Issue by LymanZerga** [BenMorris/NetArchTest#14]
We actually using NetArchTest and we are faced with some type load issues. We have a huge code base where we have folders with mixed content (c++ as well as c# assemblies). For the purpose of loading assemblies from multiple folders you have provided a ctor recently. (not yet available in nuget.org).
But when using this, we are geting BadImageFormat exceptions, since we do have mixed assemblies inside our application (c++, c#). Can you catch those exceptions during assembly load?

Currently we are loading every type (TypeDefinition) on our own and creating a Types class instance via reflection (we know this is ugly but currently the only way to get ArchUnit working for us).

**Comment by BenMorris** [comment]
Seems reasonable to me.

I assume you mean the statement AssemlyDefinition.ReadAssembly() in Types.cs? Do we need to add empty error handlers to all the occurrences of the statement (there are five)?

**Comment by LymanZerga** [comment]
Hi Ben,

yes I mean the AssemblyDefinition.ReadAssembly() in Types.cs. We do not need error handlers for that, but maybe the are usefull for other clients.

**Comment by BenMorris** [comment]
Hi Lori - I don't quite understand what sort of change you're asking for. I can't reproduce this problem so am driving a little blind here.

Are you trying to load assemblies that cannot be loaded by AssemblyDefinition.ReadAssembly()? 

Are you happy to just ignore these assemblies and have the methods only load those assemblies it can read?

**Comment by LymanZerga** [comment]
Yes exactly.  Just ignore the assemblies which are not readable.

**Comment by BenMorris** [comment]
This has been implemented, covered with a test and included in a new release (1.2.1).

**Comment by LymanZerga** [comment]
Thanks for the new version Ben. Everything works as expected.
