### ISSUE TITLE
Determining FailingTypes is incorrect when using ShouldNot

### ISSUE THREAD

**Issue by timjansenortec** [BenMorris/NetArchTest#15]
I have a case where ConditionList.GetResult() determines that success is false, but the failingTypes sequence in the TestResult instance is empty.

My test looks like this:
            var types = Types.InCurrentDomain();
            var result = types
                    .That()
                    .ResideInNamespaceMatching(nameSpace)
                    .ShouldNot()
                    .HaveDependencyOn(dependency)
                    .GetResult();

I think this is because TestResult.Failure is called with 'false', while it should consider the _should field like so:
return TestResult.Failure(_sequence.Execute(_types, selected: !_should).Select(t => t.ToType()));

**Comment by BenMorris** [comment]
That's a good spot - thanks.

This has been fixed and covered with a unit test in this commit: https://github.com/BenMorris/NetArchTest/commit/99889708a443bd7eb939e348c416b2d7494b5e72

Will push out a release at the end of this weekend once the last remaining issue has been closed.

**Comment by timjansenortec** [comment]
Tnx for the fast follow-up!
