### ISSUE TITLE
BeNestedPublic

### ISSUE THREAD

**Issue by kl1mm** [BenMorris/NetArchTest#20]
Hi there,
first of all i like to say: cool libaray thanks a lot. 

I woud like to check a rule where i have a nested public class and a nested internal/private class
unfortunately, that does not seem possible.
So i need something like -> BeNestedPublic. :) 

One step further would be a custom condition where i could put in a Func<IEnumerable<TypeDefinition>, bool> so i am able to  implement custom rules for types.
That would be nice?

Would it be possible for one of the next releases?
Thanks kl1mm

**Comment by BenMorris** [comment]
Hi - thanks for the issue.

Distinguishing between public and private nested classes is certainly doable - I'll have a think about the an appropriate syntax that doesn't involve breaking change.

As for custom rules... well... _maybe_. I am naturally suspicious of this kind of loose contract. It tends to be hard to test and could end up breaking pretty much anything.

Do you have any specific use cases in mind for this?

**Comment by kl1mm** [comment]
Hi BenMorris,
thanks for your quick reply.

> As for custom rules... well... maybe. I am naturally suspicious of this kind of loose contract. It tends to
> be hard to test and could end up breaking pretty much anything.
> Do you have any specific use cases in mind for this?

That's right, of course, but it would make it even more flexible

```
var result = Types.InAssembly(Assembly.Load("assembly.dll"))
    .Should()
    .HaveCustomRule(t => t.IsValueType && t.HasPrivateCtor()); // "HasPrivateCtor" could be an extension method
```
best regards kl1mm

**Comment by BenMorris** [comment]
The nested rules have been added in as BeNestedPublic and BeNestedPrivate.

Will have a look into adding the value type and constructor methods, but want to avoid custom rules as they form too coarse a contract.

**Comment by kl1mm** [comment]
Hi Ben, thanks for the new Release.

As i mentioned:
>  I woud like to check a rule where i have a nested public class and a nested **internal**/private class

Public/Privte 👍 
Internal 👎 

With the possibility to check a predicate like in my suggestion (HaveCustomRule) it would be very easy to do all stuff i needed.

Just for explanation:
I have a class structure looking something like that and want to test the visibility of the nested classes. Request should be public and Handler and Validator should be internal. Some times there could be private classes too. It is also important for me to test the visibility of the ctor's.
```csharp
public class UseCase
{
	public class Request // must be public
	{
		//... some props
	}

	internal class Handler // must be internal
	{
		public async Task Handle()
		{
			// some code to handle request
		}
	}

	internal class Validator // must be internal
	{
		private Validator() // must be private
		{
			// some code to validate request
		}
	}
}
```
For reasons of simplicity I have omitted the derivations.

thanks Ben, take care and have a nice day, greeting from Germany, kl1mm
