### ISSUE TITLE
Add Not Condition

### ISSUE THREAD

**Issue by LymanZerga** [BenMorris/NetArchTest#21]
Hi there,
**first of all I also like to say thanks a lot to that very cool library.**
For the next release it is maybe a good Idea to add a Not Condition which negates the subsequent condition. This would reduce the number of methods a lot, since there is no need to double up any method by NotXXX anymore. I know this would result in a breaking change, but leads to reducing the number of similar code a lot (when also removing all NotXXX methods as well as adding the Not condition). As you have a lot of tests, this change should be easy to test. If you like to, I would do that on a separat branch.

`Types.InCurrentDomain().That().HaveDependencyOn("System.Data").Should().NotResideInNamespace("NetArchTest.SampleLibrary.Data")` 
_will then be equivalent to_
`Types.InCurrentDomain().That().HaveDependencyOn("System.Data").Should().Not().ResideInNamespace("NetArchTest.SampleLibrary.Data")`

**Comment by BenMorris** [comment]
Hi - this was achieved by implementing methods as pairs - i.e. `NameMatching` and `NotHaveNameMatching`. This is much easier to implement but IMHO it gives rise to clearer syntax. Chaining together lots of `Should()` and `Not()` calls can get confusing.
