### ISSUE TITLE
Throw exception if no types are passed to For(...)

### ISSUE THREAD

**Issue by paulroho** [BenMorris/NetArchTest#24]
First thank you for providing that pretty neat project.

While playing around with NetArchTest in a tiny sample project I had a hard time when the evaluation of a policy did not find an obviously existing issue. I evaluated the policy in a unit test and used `For(Types.InNamespace(...))` to define the types of the rule.
With a little bit of debugging I found out that the problem was that my production assembly with the design issue was not even loaded in the AppDomain and therefore the types in it not evaluated.
Although this will probably be not so much of a problem in realistic elaborated uses of the library, it would be helpful to get a strong feedback if there are not types matching the parameters chosen.
As I would not expect people to write checks in advance without having a single matching type in it, I think throwing an exception should be fine.

What do you think?

I would be happy to provide a PR for that.

**Comment by paulroho** [comment]
I would be grateful if you would share your thoughts on that issue.
Thank you.

**Comment by BenMorris** [comment]
Apologies for the delayed response.

I would be reluctant to throw an exception for something like this. It would feel like using exceptions for validation?

I'm also uncomfortable with the potential for breaking change. If we throw an exception if the original collection of types is empty we may suddenly start to break a lot of peoples' unit tests. 

We could take a less intrusive approach and add a property to the `TestResult` class. However, this will mean passing some kind of flag down the stack of predicates and conditions as they are executed - we'll end up adding a lot of complexity for something that feels like an edge case.
