### ISSUE TITLE
Using Types.InAssembly returns compiler generated classes

### ISSUE THREAD

**Issue by mvput** [BenMorris/NetArchTest#34]
**Problem:** 

When using the `Types.InAssembly(assembly)` the compiler-generated types are included as well.

**Reproduce:** 

For example when you have a few classes like the following.
Using .NET Core 3.1 and .NET Standard 2.1 libraries. 

```
public class PingHandler : IRequestHandler<Ping, Pong>
{
}
```
The type is visible in the assembly, also the compiler-generated display classes. So when you create a policy for example with `HaveNameEndingWith("Handler")` it does not work. 

**Possible solution:**

Filter the types based on the `CompilerGeneratedAttribute `. You can do this using the following code:
```
assembly.GetTypes().Where(x =>!x.IsDefined (typeof(CompilerGeneratedAttribute), false));
```

**Comment by BenMorris** [comment]
Hi - I believe this has been taken care of in this pull request: https://github.com/BenMorris/NetArchTest/pull/31

It hasn't been released yet but I will sort that out now.
