### ISSUE TITLE
.netFramework4.5.2 is not supported by 1.2.4 version

### ISSUE THREAD

**Issue by gargankurg** [BenMorris/NetArchTest#37]
I came across to one of the situation where we are planning to use .NetArchTest tool but that is a legacy project with .netFramekwork 4.5.2 and when I am planning to add .netArchTest in my project it gives me below error so, do you know any resolution for the same. 

I know it works with 4.7.2 however I am not planning to upgrade the framework as of now. 

I tried all the available version from the list shown on the NuGet Package Manager however all of them gave me the below error. 

Also I am not sure if anybody else faced this issue. 

==================
Could not install package 'NetArchTest.Rules 1.2.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Vertygo** [comment]
Readme states that:
`It is a .Net Standard 2.0 library that is compatible with .Net Framework 4.6.1 or better and .Net Core 2.0 or better.`

In order to be compatible with .NET Framework 4.5.2, NetArchTest needs to depend on netstandard1.2 instead of netstandard2.0.
NetArchTest uses some API from `Assembly` and `AppDomain` that came in netstandard2.0 and it also depends on version of `Mono.Cecil` that depends on netstandard2.0.

**Comment by gargankurg** [comment]
Thank you so much for your updates.

I am thinking a workaround for this but not sure if this would work or I may come across any issue in the future so please guide me. 

I am thinking to add a new project with 4.7.2 .netframework just to write the Architecture UnitTest cases. Will this approach work? Upgrading the framework in the original project is not an option for us.

**Comment by BenMorris** [comment]
Hi - I'm afraid it's not going to be possible to get this working directly with .Net Standard 1.3. The intention was to make the the library compatible with both .Net Core and .Net Framework - hence the use of Mono.Cecil under the hood for handling dependency searching.

As you suggest, writing your tests in a .Net Framework 4.7.2 project is the workaround here. I have set up a test project that runs tests against 4.5.2 with no problems.
