### ISSUE TITLE
Strange behavior when applying Or/And condition

### ISSUE THREAD

**Issue by Vertygo** [BenMorris/NetArchTest#38]
Hi @BenMorris , I have been playing with the `NetArchTest` and while doing so I have run into two cases that might look like a bug.

In first example I have used `And` condition where GetResult() `IsSuccess` is returning `false` with the empty `FailingTypes` list.

```
namespace Test
{
    public class Dependency
    {
    }

    public class ClassA
    {
        public Dependency Dep { get; set; }
    }
}

namespace Test.B
{
    public class ClassB
    {
        public Dependency Dep { get; set; }
    }

}

...

    var result = Types.InNamespace("Test")
        .That()
        .HaveDependencyOn(typeof(Dependency).FullName)
        .Should()
        .HaveName(typeof(ClassA).Name)
        .And()
        .ResideInNamespace(typeof(ClassB).Namespace)
        .GetResult();
```

In second example I'm using `Or` condition where GetResult() `IsSuccess` is returning `false` but all three classes show up in a `FailingTypes` list.

```
namespace Test
{
    public class Dependency
    {
    }

    public class ClassA
    {
        public Dependency Dep { get; set; }
    }
}

namespace Test.B
{
    public class ClassB
    {
        public Dependency Dep { get; set; }
    }

}

namespace Test.D
{
    public class ClassD
    {
        public Dependency Dep { get; set; }
    }
}

...

    var result = Types.InNamespace("Test")
        .That()
        .HaveDependencyOn(typeof(Dependency).FullName)
        .Should()
        .HaveName(typeof(ClassA).Name)
        .Or()
        .ResideInNamespace(typeof(ClassB).Namespace)
        .GetResult();

```

**Comment by BenMorris** [comment]
Thanks for this - a good spot and really clear example. This should be fixed in the following pull request: https://github.com/BenMorris/NetArchTest/pull/39 

With this fix, the first example will return both types in the failing list, while the second example will only return Test.D.ClassD.

I'll get this released over the next couple of days.
