### ISSUE TITLE
When you planning to update nuget package?

### ISSUE THREAD

**Issue by vdasus** [BenMorris/NetArchTest#44]
My code is not working as expected with last nuget package, but it's ok with NetArchTest compiled from source code.

I think it's bad idea to search what is the problem on my or netarch code, because i'm totally newbie in netarch and question about plans of nuget package upgrade. Thank you

``` c#
[Fact]
        public void Domain_Classes_Should_Not_Depend_On_DomainServices_Layer()
        {
            var types = Types.InAssembly(ApplicationAssembly);
            
            var result = types
                .That()
                .ResideInNamespaceMatching(@"^gOldCleaner\.Domain$")
                .Should()
                .NotHaveDependencyOn("gOldCleaner.DomainServices")
                .GetResult();

            result.FailingTypeNames.Should().BeNullOrEmpty("Domain can't depend on DomainServices");
            result.IsSuccessful.Should().BeTrue();
        }
```

just for testing added FolderItemService in gOldCleaner.DomainServices in the same assembly, but with different namespace
```c#
namespace gOldCleaner.Domain
{
    public sealed class FolderItem: ValueObject
    {
        public FolderItem(string description, string folderPath, string searchPattern, TimeSpan deleteAfter, bool isDeleteEmptyFolders
//add this just to test that dependency catched by test
        , FolderItemService svc = null)
        {
```

With last nuget (1.2.4) package result is always false positive (dependency not catched), with source code all is ok, dependency catched.

**Comment by BenMorris** [comment]
Hi - sorry for the delay in the new package but I wanted to review and include a fairly large set of changes to the dependency searching (see #36). Now all done and dusted so I should get a new package out tomorrow.
