### ISSUE TITLE
Is it possible to create rule to prevent classes to depend on each other

### ISSUE THREAD

**Issue by Vertygo** [BenMorris/NetArchTest#50]
Hi,
Java ArchUnit has a concept of [slices ](https://blog.jdriven.com/2018/10/testing-the-architecture-archunit-in-practice/) and I was wondering if something similar is possible to do in NetArchTest? This comes handy in cases where you want to prevent classes from the same layer/namespace to depend on each other.

**Comment by BenMorris** [comment]
Replicating the slice construct in ArchUnit would be a fairly substantial piece of work.

A simpler approach might be to add method overloads to the dependency checking methods that make it easier to pass in collections of types. This would allow you to manually define "slices" and use them to generate rules.

Something like...

```
// Define "slices"
var dataSlice = Types.InCurrentDomain()
    .That().ResideInNamespace(("NetArchTest.SampleLibrary.Data"));

var presentationSlice = Types.InCurrentDomain()
    .That().ResideInNamespace(("NetArchTest.SampleLibrary.Presentation"));

// Prevent one layer from referring to another
var result = dataSlice
    .ShouldNot().HaveDependencyOnAny(presentationSlice)
    .GetResult();
```
