### ISSUE TITLE
Reference types defined by part of the namespace

### ISSUE THREAD

**Issue by electronickai** [BenMorris/NetArchTest#51]
Hi,
in ArchUnit you can refer to packages by using a part of the name `..persistence..`.
In NetArchTest it seems that you have always to provide the complete name of the namespace.

How would you refer to classes in persistence namespaces that are distrubuted in different functional areas like `MyApp.User.Persistence` and `MyApp.Booking.Persistence`?
(e.g. to prevent any persistence classes from accessing any business service class)

**Comment by ajedwards** [comment]
You should be able to use the `ResideInNamespaceMatching()` method to match a regular expression, Kai.

For your examples, try something like:

```
types.Should().ResideInNamespaceMatching(@"(.*)?Persistence(.*)?")
```
