### ISSUE TITLE
Rules Extensibility 

### ISSUE THREAD

**Issue by sm-g** [BenMorris/NetArchTest#54]
I would like to write custom predicates/conditions. 

Something like

```
Types.InAssembly(asm)
   .That().Are(type => true)
   .Should()
   .Be(type => true)
```

would be OK for the first time. Extensions support like

```
Types.InAssembly(asm)
   .That().AreSuitableForMe()
   .Should()
   .HaveGoodNames()
```

would be brilliant.

**Comment by karelg** [comment]
Very nice library, but the lack of extension points is very limiting right now.

**Comment by BenMorris** [comment]
This could be done, though we'll have to take care over the interface (see my comments on PR #61)

It would be useful to understand a little more about the kinds of use cases we want to support here. What kids of rules would you want to use an extensible interface for?

**Comment by FrankRaiserKIS** [comment]
We would be fine with `Have()` and `Be()`, but also if it is changed to `MeetCustomRule`. Either way, is there any plan on when (either of) this will be available as a proper release version?

**Comment by BenMorris** [comment]
I will implement this as a method that allows custom rules to be created as external classes that confirm to a simple interface.

As mentioned before it would be useful to have some examples of the kind of scenarios this will be used for.

Am planning to get a new release out in the next week or two. There are a few chunky pull requests that I need to check through first.

**Comment by BenMorris** [comment]
See #65
