### ISSUE TITLE
HaveCustomAttribute does not check inherited attributes

### ISSUE THREAD

**Issue by sm-g** [BenMorris/NetArchTest#55]
Would be nice to have rule like `BeDecoratedWithOrInherit` from https://fluentassertions.com/typesandmethods/

**Comment by NeVeSpl** [comment]
Two new rules: HaveCustomAttributeOrInherit and NotHaveCustomAttributeOrInherit were added in #60

**Comment by BenMorris** [comment]
This has been approved now and will be in the next release.
