### ISSUE TITLE
Enable the specification of string comparison strategies to be used when matching strings

### ISSUE THREAD

**Issue by RyanMarcotte** [BenMorris/NetArchTest#66]
Given the following `PredicateList`:

``` csharp
Types.InCurrentDomain()
	.That()
	.AreClasses()
	.And()
	.HaveNameEndingWith("Entity")
```

... the following class is picked up, which is undesired:

``` csharp
public class SomeIdentity
{
	// properties omitted for brevity
}
```

Seems like it should be as straightforward as providing an overload for the appropriate methods that accepts `IEqualityComparer<string?>`.

``` csharp
Types.InCurrentDomain()
	.That()
	.AreClasses()
	.And()
	.HaveNameEndingWith("Entity", StringComparer.Ordinal)
```

If I get the go-ahead for this, I can open a PR.

**Comment by BenMorris** [comment]
Yes - this looks like a good idea to me.

**Comment by RyanMarcotte** [comment]
Closing since the associated PR has been merged
