### ISSUE TITLE
ImplementInterface does not select types implementing that interface

### ISSUE THREAD

**Issue by sm-g** [BenMorris/NetArchTest#69]
i.e. interfaces from https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequest.cs

and my code:

```
public class MyQuery : IRequest<Guid>
{
}
```

and failing test:

```
Types.InAssembly(MyAssembly)
            .That()
            .ImplementInterface(typeof(IBaseRequest))
            .GetTypes().Should().Contain(typeof(MyQuery))
```

**Comment by BenMorris** [comment]
After the changes in #62:

Given the interfaces:

```
public interface IBaseRequest { }

public interface IRequest<T> : IBaseRequest { }

public class MyQuery : IRequest<string> { }
```

The following will yield MyQuery:

```
Types.InCurrentDomain()
    .That()
    .AreClasses()
    .And()
    .ImplementInterface(typeof(IBaseRequest))
    .GetTypes();
```

**Comment by NeVeSpl** [comment]
Are you sure about that? ImplementInterface() does not use dependency search, so I would be very surprised if #62 would change anything in this mater. The same goes for #71

**Comment by BenMorris** [comment]
It's more accurate to say that I can't replicate this on the current version of the master code branch.

Perhaps the problems are more down to usage and interpretation.

**Comment by Yaevh** [comment]
the issue seems to be caused by Mono.Cecil and its handling of interfaces, see https://github.com/jbevain/cecil/issues/625
