### ISSUE TITLE
Add ability to check if classes are static

### ISSUE THREAD

**Issue by RyanMarcotte** [BenMorris/NetArchTest#89]
The following methods exist as predicates:
- `AreInterfaces` / `AreNotInterfaces`
- `AreAbstract` / `AreNotAbstract`
- `AreSealed` / `AreNotSealed`

Mind if I go ahead and add `AreStatic`, `AreNotStatic` methods to `Predicates`?  [The check is a little more involved](https://stackoverflow.com/a/1175901).

**Comment by BenMorris** [comment]
Implemented in  #90 - thanks for the issue and pull request.
